config/routes.rb
SendMeFiles::Application.routes.draw do
  root 'uploads#new'
  resources :uploads, only: %i[new create]

end

app/models/upload.rb
class Upload
  def initialize(params)
    puts "Got params: #{params}"
    @url = params[:url]
    @filename = params[:filename]
  end

  def save!
    sns = AWS::SNS.new
    topic = sns.topics[Rails.application.config.sns_topic]
    topic.publish("You have a new file named #{@filename}. \n\n"\
                  "Download your file here: #{@url}",
                  subject: "New file: #{@filename}")
  end

  def confirmation_message
    "Your file #{@filename} has been sent!"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @allowed = if Rails.application.config.password
                 params[:a] == Rails.application.config.password
               else
                 true
               end
  end

  def create
    upload = Upload.new(params)
    upload.save!
    respond_to do |format|
      format.json { render json: {message: upload.confirmation_message} }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>Send <%= Rails.application.config.name %> Files</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Send Phil files, no matter how large." />
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" rel="stylesheet" type="text/css" />
    <!--[if lte IE 8]><%= javascript_include_tag "html5shiv"%><![endif]-->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag :modernizr %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lte IE 8]><%= stylesheet_link_tag "ie8.css" %><![endif]-->
  </head>
  <body class="homepage">

    <h1>Send <%= Rails.application.config.name %> Files</h1>

    <div id="content" class="inner">
      <%= yield %>
    </div>


  </body>
</html>

app/views/uploads/new.html.erb
<% if @allowed %>
<script id="template-upload" type="text/x-tmpl">
<div id="file-{%=o.unique_id%}" class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<h2>Choose a file from your computer</h2>

<div id="multiple">You can choose more than one file if you want.</div>

<%= s3_uploader_form callback_url: uploads_path, callback_param: "upload[url]", id: "uploader" do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>
<% else %>
<p>It looks like you ended up here by mistake.</p>
<% end %>